function shuffleWords(str) {
  const words = str.split(';').map(word => word.trim()); // Разбиваем строку по точке с запятой и убираем пробелы
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1)); // Генерируем случайный индекс
    [words[i], words[j]] = [words[j], words[i]]; // Меняем местами элементы
  }
  return words.join('; '); // Собираем строку обратно через точку с запятой
}

const input = "warum; lang; Was interessiert Sie?; wollen; zumachen; gehen; freundlich; der Tisch / Tische; schließlich; der Spross / Sprösslinge; kaufen; das Leben; nur; Geschäft; schließen; hören; anrufen; das Brot / Brote; vielleicht; morgen; die Aufgabe / Aufgaben; neu / neue (ной); Der hund / hunde; der Planet / Planeten; früh; schön; schlafen; essen; die Tasche / Taschen; machen; die Schule / Schulen; die Stunde / Stunden; das Bad / Bäder; der Stock / Stöcke; heute; die Hand / Hände; der Garten / Gärten; zusammen; billig; mit (+ Dativ); die Wohnung (воонун) / Wohnungen (вонунен); der junge / jungen; ; Woher kommst du?; der Schlüssel / Schlüssel; das Krankenhaus / Krankenhäuser; wo; lernen; die Katze / Katzen; das Abenteuer / Abenteuer; müssen; der Duft / Düfte; das Zimmer / Zimmer; einladen; der Weg (виg) / Wege; zurück-; ausgehen; in; rufen; das Fenster / Fenster; alt; hell; die Arbeit / Arbeiten; der Teil / Teile; die Küche / Küchen; fliegen; der Vulkan / Vulkane; harte; sein; leise; schlecht; unter (+ Akk/Dat); jetzt; will; bald; ein-; die Tür (тюа) / Türen; aber; das Tier / Tiere; an-; Meine Hobbys sind Programmieren und Deutsch, du?; wie; die Warmmiete / Warmmieten; das Buch / Bücher; draußen; schwierig; schützen; sauber; denken; auf; fernsehen; krank / kranke; wohnen; das Weltall / Weltalle; aufstehen; der Abend / Abende; suchen; die Zeit / Zeiten; der Lehrer / Lehrer; aufhören; schreiben; der Wind / Winde; da; wachsen; für (+ Akkusativ); singen; aufmachen; Wie alt bist du?; kalt; die Uhr (уа) / Uhren; warten; klein; Wie geht es dir?; schnarcht; Zwei von ihnen; Hausaufgaben; der Geburtstag / Geburtstage; verstehen; können; teuer (тоя); die Stadt / Städte; Reparieren; sehen; jader (йида); nett; spielen; der Kopf / Köpfe; das Haus / Häuser; Alles ist gut, und ihnen?; bei (+ Dativ); sehr (зея); los-; mögen; gestern; kommen; nach (+ Dativ); das Bett / Betten; hier (хия); die Rose / Rosen; das Auto / Autos; langsam; die Lampe / Lampen; mitkommen; brauchen; laufen; der Freund / Freunde; das Hochhaus / Hochhäuser; gut; süß; das Lied / Lieder; Durst; ohne (+ Akk); Anfangs; bezahlen; oft; mit-; auf-; die Miete / Mieten; immer; öffnen; dürfen; die Straße / Straßen; stehen; der Stolz; der Balkon / Balkone; die Brücke / Brücken; die Nachricht / Nachrichten; Schmetterling; haben; aus-; die Asche / Aschen; spazieren; groß; über (+ Akk/Dat); aufstehen; drinnen; wichtig (вихтигх); im dritten stock; wann; selten; das Handy / Handys; was; arbeiten; weil; fernsehen; sollen; gießen; das Heim / Heime; das Essen; Bußgeld; die Mutter / Mütter; finden; der Stuhl / Stühle; trinken; fahren; schnell; Huhn (хун); lesen; die Ding / Dinge (диннь / динне); die Frage / Fragen; flaumig"

console.log(shuffleWords(input));