function shuffleWords(str) {
  const words = str.split(';').map(word => word.trim()); // Разбиваем строку по точке с запятой и убираем пробелы
  for (let i = words.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1)); // Генерируем случайный индекс
    [words[i], words[j]] = [words[j], words[i]]; // Меняем местами элементы
  }
  return words.join('; '); // Собираем строку обратно через точку с запятой
}

const input = "Was interessiert Sie?; hell; der Freund / Freunde; der Weg (виg) / Wege; freundlich; die Lampe / Lampen; lernen; gestern; will; die Katze / Katzen; hier (хия); klein; für (+ Akkusativ); die Arbeit / Arbeiten; die Uhr (уа) / Uhren; da; weil; die Küche / Küchen; Wie alt bist du?; trinken; vielleicht; nett; kommen; gehen; gut; draußen; das Bett / Betten; wann; warum; haben; essen; schön; das Handy / Handys; selten; nach (+ Dativ); oft; wohnen; wo; schlafen; spazieren; bei (+ Dativ); die Straße / Straßen; unter (+ Akk/Dat); sehen; finden; Alles ist gut, und ihnen?; kalt; die Zeit / Zeiten; das Zimmer / Zimmer; harte; sehr; sauber; schnell; spielen; Durst; das Auto / Autos; wichtig (вихтигх); flaumig; der junge / jungen; Woher kommst du?; wie; was; süß; morgen; über (+ Akk/Dat); krank; Meine Hobbys sind Programmieren und Deutsch, du?; aber; ohne (+ Akk); schnarcht; denken; teuer (тоя); das Leben; auf; die Ding / Dinge (диннь / динне); heute; lesen; in; schlecht; der Tisch / Tische; langsam; Wie geht es dir?; der Stuhl / Stühle; das Bad / Bäder; nur; mit (+ Dativ); die Tür (тюа) / Türen; drinnen; die Wohnung (воонун) / Wohnungen (вонунен); die Tasche / Taschen; jetzt; hören; kaufen; sein; das Fenster / Fenster; bald; neu / neue (ной); leise; machen; immer; Der hund / hunde; arbeiten; Bußgeld; groß; fahren; lang; Geburtstag; der Schlüssel / Schlüssel; Hausaufgaben; Geschäft; zusammen; das Essen; Huhn (хун); das Brot / Brote; der Teil / Teile; das Haus / Häuser; das Hochhaus / Hochhäuser; der Stock / Stöcke; im dritten stock; der Balkon / Balkone; bezahlen; die Miete / Mieten; die Warmmiete / Warmmieten; suchen; der Garten / Gärten; brauchen; die Schule / Schulen; der Lehrer / Lehrer; die Stadt / Städte; das Buch / Bücher; die Hand / Hände; die Nachricht / Nachrichten; die Frage / Fragen; schreiben; warten; alt; das Tier / Tiere; die Stunde / Stunden; der Kopf / Köpfe; öffnen; schließen; verstehen; schwierig; die Aufgabe / Aufgaben; die Brücke / Brücken; laufen; singen; das Lied / Lieder; fliegen; billig;"

console.log(shuffleWords(input));